version: '3.8'
services:
  accounts:
    build:
      context: ./accounts
    ports:
      - "8080:8080"

  transactions:
    build:
      context: ./transactions
    ports:
      - "8081:8081"

  gateway:
    build:
      context: ./gateway
    ports:
      - "4000:8080"
